seed: 0
process: pois
t_max: 1000
dt: 0.01
n_persons: 30
n_train: 5
n_test: 2
context_intensity_pois_min:
  - 0.1
  - 1.
context_intensity_pois_factors:
  - 10
  - 3

# regulator is a function which changes the rate over time
non_regulator_outliers_prob: 0.1
