seed: 0
process: pois
t_max: 100
dt: 0.1
n_persons: 30
n_train: 10
n_test: 10
context_intensity_pois_min:
  - 0.02
  - 0.1
context_intensity_pois_factors:
  - 10
  - 10

# regulator is a function which changes the rate over time
non_regulator_outliers_prob: 0.5
