seed: 0
n_persons: 30
n_train: 10
n_test: 10
t_max: 100
dt: 0.1
nhid: 64
context_intensity_pois_min:
  - 0.004
  - 0.01
context_intensity_pois_factors:
  - 100
  - 100
non_regulator_outliers_prob: 0.1
use_personalisation: true
use_context: true
